### ISSUE TITLE
Question for 201708_CrossU01_Rebuttal_Code.R

### ISSUE THREAD

**Issue by hemingwang** [rspengle/CrossU01_exRNA_Manuscript2017#1]
Hi Spengler，
Recently, I found your paper "Comprehensive multi-center assessment of small RNA-seq methods for quantitative miRNA profiling". So I want to run it
 
When I run the code(201708_CrossU01_Rebuttal_Code.R)(line 212)
counts.dt.synth.endog.miRs <- subset(counts.dt.endog.miRs.all, pool%in%synth.files)

But I meet a trouble:
Error in pool %in% synth.files : object 'pool' not found

I am looking forward to you reply!

yours Sincerely,

heming wang

**Comment by rspengle** [comment]
I'm sorry you ran into trouble with the code. I was unable to reproduce your error. I had made some changes to the code for the manuscript that I forgot to push to github, but I don't think that part of the code was affected. 

How are you running the code? Are you executing the file from the command line or interactively? This code was meant to be run interactively, so I would recommend trying to run it within RStudio to see if that works, or if it gives other errors. 

If you still get an error interactively, you can check a couple other things.
- What version of the data.table package do you have installed? Make sure that's updated and try again. I believe I use v1.11.4 in the packrat library for this project.
- If updating data.table doesn't work, you can modify line 212. Changing it to either or these should work.
counts.dt.synth.endog.miRs <- counts.dt.endog.miRs.all[synth.files, on="pool"]
or
counts.dt.synth.endog.miRs <- counts.dt.endog.miRs.all[pool%in%synth.files]

Good luck
Ryan

**Comment by hemingwang** [comment]
Thanks for your patience helping me!
I used the RStudio(1.1.463) to running the code.
The version of package(data.table) in my computer is  1.11.4
I modify line 212, but it doesn't work.
This is my error messages:
> counts.dt.synth.endog.miRs <- subset(counts.dt.endog.miRs.all, pool%in%synth.files)
Error in pool %in% synth.files : object 'pool' not found
> counts.dt.synth.endog.miRs <- counts.dt.endog.miRs.all[synth.files, on="pool"]
Error in `[.data.table`(counts.dt.endog.miRs.all, synth.files, on = "pool") : 
  Column(s) [pool] not found in x
> counts.dt.synth.endog.miRs <- counts.dt.endog.miRs.all[pool%in%synth.files]
Error in pool %in% synth.files : object 'pool' not found

Best wishes
heming wang

**Comment by rspengle** [comment]
So that indicates that counts.dt.endog.miRs.all doesn't have a column named "pool". Can you send the output you get from 
head(counts.dt.endog.miRs.all)
and
head(CROSS.U01.METADATA.ALL)

**Comment by hemingwang** [comment]
Hi Ryan,
My result is:
> head(counts.dt.endog.miRs.all)
Null data.table (0 rows and 0 cols)

> head(CROSS.U01.METADATA.ALL)
                      FileBaseName  Lab lib.method.detail lib.method.simple   pool replicate
1: sample_01_SynthA-1-TruSeq_fastq Lab6            TruSeq            TruSeq SynthA         1
2: sample_02_SynthA-2-TruSeq_fastq Lab6            TruSeq            TruSeq SynthA         2
3: sample_03_SynthA-3-TruSeq_fastq Lab6            TruSeq            TruSeq SynthA         3
4: sample_04_SynthA-4-TruSeq_fastq Lab6            TruSeq            TruSeq SynthA         4
5: sample_05_SynthB-1-TruSeq_fastq Lab6            TruSeq            TruSeq SynthB         1
6: sample_06_SynthB-2-TruSeq_fastq Lab6            TruSeq            TruSeq SynthB         2
   Lane                                                runID.genomeMapped
1:    1 ALL_LABS-TRUSEQ_Synth_AND_Plasma_VS_Genome-2017-7-24-16%3A59%3A10
2:    1 ALL_LABS-TRUSEQ_Synth_AND_Plasma_VS_Genome-2017-7-24-16%3A59%3A10
3:    1 ALL_LABS-TRUSEQ_Synth_AND_Plasma_VS_Genome-2017-7-24-16%3A59%3A10
4:    1 ALL_LABS-TRUSEQ_Synth_AND_Plasma_VS_Genome-2017-7-24-16%3A59%3A10
5:    1 ALL_LABS-TRUSEQ_Synth_AND_Plasma_VS_Genome-2017-7-24-16%3A59%3A10
6:    1 ALL_LABS-TRUSEQ_Synth_AND_Plasma_VS_Genome-2017-7-24-16%3A59%3A10
                                             runID.calibrator InputReads
1: ALL_LABS-TruSeq-Synth_VS_CALIBRATOR-2017-7-24-17%3A01%3A10   17494155
2: ALL_LABS-TruSeq-Synth_VS_CALIBRATOR-2017-7-24-17%3A01%3A10   18251010
3: ALL_LABS-TruSeq-Synth_VS_CALIBRATOR-2017-7-24-17%3A01%3A10   15910361
4: ALL_LABS-TruSeq-Synth_VS_CALIBRATOR-2017-7-24-17%3A01%3A10   18031739
5: ALL_LABS-TruSeq-Synth_VS_CALIBRATOR-2017-7-24-17%3A01%3A10   13001542
6: ALL_LABS-TruSeq-Synth_VS_CALIBRATOR-2017-7-24-17%3A01%3A10   14643899
   SuccessfullyClippedReads adapter.confidence excerpt.qc.call.genomeMapped lane  file.type
1:                 16972453               HIGH                         PASS L.NA miRNASense
2:                 17797287               HIGH                         PASS L.NA miRNASense
3:                 15462580               HIGH                         PASS L.NA miRNASense
4:                 17562023               HIGH                         PASS L.NA miRNASense
5:                 12503174               HIGH                         PASS L.NA miRNASense
6:                 14121995               HIGH                         PASS L.NA miRNASense
                                                                                       file.path
1: ./data/mirna_sense/synthetic/sample_01_SynthA-1-TruSeq_fastq_readCounts_miRNAmature_sense.txt
2: ./data/mirna_sense/synthetic/sample_02_SynthA-2-TruSeq_fastq_readCounts_miRNAmature_sense.txt
3: ./data/mirna_sense/synthetic/sample_03_SynthA-3-TruSeq_fastq_readCounts_miRNAmature_sense.txt
4: ./data/mirna_sense/synthetic/sample_04_SynthA-4-TruSeq_fastq_readCounts_miRNAmature_sense.txt
5: ./data/mirna_sense/synthetic/sample_05_SynthB-1-TruSeq_fastq_readCounts_miRNAmature_sense.txt
6: ./data/mirna_sense/synthetic/sample_06_SynthB-2-TruSeq_fastq_readCounts_miRNAmature_sense.txt
   Notes lab.libMethod.pool.replicate lab.libMethod.pool lab.libMethod.replicate lab.libMethod
1:  <NA>         TruSeq.Lab6.SynthA.1 TruSeq.Lab6.SynthA           TruSeq.Lab6.1   TruSeq.Lab6
2:  <NA>         TruSeq.Lab6.SynthA.2 TruSeq.Lab6.SynthA           TruSeq.Lab6.2   TruSeq.Lab6
3:  <NA>         TruSeq.Lab6.SynthA.3 TruSeq.Lab6.SynthA           TruSeq.Lab6.3   TruSeq.Lab6
4:  <NA>         TruSeq.Lab6.SynthA.4 TruSeq.Lab6.SynthA           TruSeq.Lab6.4   TruSeq.Lab6
5:  <NA>         TruSeq.Lab6.SynthB.1 TruSeq.Lab6.SynthB           TruSeq.Lab6.1   TruSeq.Lab6
6:  <NA>         TruSeq.Lab6.SynthB.2 TruSeq.Lab6.SynthB           TruSeq.Lab6.2   TruSeq.Lab6
>

**Comment by rspengle** [comment]
So it looks like it's failing during the step where it imports the count data files. Make sure your working directory is the top level of this project directory on your computer. The file paths are all relative. Also just confirm that all the data files were downloaded.
Did the data files get downloaded? They should be in the data folder. 
Once youve confirmed that, running this should give all TRUE counts:
CROSS.U01.METADATA.ALL[, table(file.exists(file.path))]

**Comment by hemingwang** [comment]
Thanks for your patience helping me!
I redownload the data and solve the problems.

Thank you!
Heming

**Comment by rspengle** [comment]
Happy to help. Let me know if you have any other issues.
